apiVersion: v2
name: jitsu
type: application

# Chart version is set automatically as part of the release process
version: 0.0.0
appVersion: 2.8.2

dependencies:
  - name: postgresql
    version: ^16.0.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: ^20.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: kafka
    version: ^30.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kafka.enabled
  - name: mongodb
    version: ^16.0.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: clickhouse
    version: ^6.2.27
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: clickhouse.enabled
