apiVersion: v2
name: jitsu
type: application

# Chart version is set automatically as part of the release process.
# See releases on GitHub to find the latest version.
version: 0.0.0
appVersion: 2.8.2

dependencies:
  - name: postgresql
    version: ^16.3.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: redis
    version: ^20.6.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
  - name: kafka
    version: ^31.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kafka.enabled
  - name: mongodb
    version: ^16.4.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.enabled
  - name: clickhouse
    version: ^7.1.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: clickhouse.enabled
