{{- if .Values.tokenGenerator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jitsu.fullname" . }}-token-generator-{{ sha1sum (toJson .Values) | substr 0 8 }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "jitsu.tokenGenerator.serviceAccountName" . }}
      containers:
        - name: token-generator
          image: "alpine/k8s:{{ .Capabilities.KubeVersion.Version | trimPrefix "v"}}"
          env:
            - name: FULLNAME
              value: {{ include "jitsu.fullname" . }}
            - name: SECRET_LENGTH
              value: {{ .Values.tokenGenerator.secretLength | default "32" | quote }}
            - name: TOKEN_LENGTH
              value: {{ .Values.tokenGenerator.tokenLength | default "32" | quote }}
            - name: SALT_LENGTH
              value: {{ .Values.tokenGenerator.saltLength | default "32" | quote }}
          command: ["sh", "-c"]
          args:
            - |
              if kubectl get secrets "$FULLNAME-tokens" > /dev/null 2>&1; then
                echo "Secret $FULLNAME-tokens already exists, skipping generation"
                exit 0
              fi
              set -e
              random_string() {
                length="$1"
                cat /dev/urandom | tr -dc 'a-zA-Z0-9_-' | head -c "$length"
              }
              hex_hash_token() {
                token="$1"
                salt="$2"
                secret="$3"
                echo -n "$token$salt$secret" | sha512sum | awk '{print $1}' | tr -d '\n'
              }
              base64_hash_token() {
                hex_hash_token "$@" | xxd -r -p | base64 -w 0 | tr -d '='
              }
              globalHashSecret=$(random_string $SECRET_LENGTH)
              ingestTokenSecret=$(random_string $SECRET_LENGTH)
              bulkerTokenSecret=$(random_string $SECRET_LENGTH)
              syncctlTokenSecret=$(random_string $SECRET_LENGTH)

              consoleAuthToken=$(random_string $TOKEN_LENGTH)
              ingestAuthToken=$(random_string $TOKEN_LENGTH)
              bulkerAuthToken=$(random_string $TOKEN_LENGTH)
              syncctlAuthToken=$(random_string $TOKEN_LENGTH)

              consoleAuthTokenSalt=$(random_string $SALT_LENGTH)
              ingestAuthTokenSalt=$(random_string $SALT_LENGTH)
              bulkerAuthTokenSalt=$(random_string $SALT_LENGTH)
              syncctlAuthTokenSalt=$(random_string $SALT_LENGTH)

              ingestAuthTokens="$ingestAuthTokenSalt.$(base64_hash_token $ingestAuthToken $ingestAuthTokenSalt $ingestTokenSecret)"
              bulkerAuthTokens="$bulkerAuthTokenSalt.$(base64_hash_token $bulkerAuthToken $bulkerAuthTokenSalt $bulkerTokenSecret)"
              syncctlAuthTokens="$syncctlAuthTokenSalt.$(base64_hash_token $syncctlAuthToken $syncctlAuthTokenSalt $syncctlTokenSecret)"

              consoleAuthTokens="$consoleAuthTokenSalt.$(hex_hash_token $consoleAuthToken $consoleAuthTokenSalt $globalHashSecret)"

              kubectl apply -f- <<EOF
              apiVersion: v1
              kind: Secret
              metadata:
                name: $FULLNAME-tokens
              type: Opaque
              stringData:
                globalHashSecret: "$globalHashSecret"

                ingestTokenSecret: "$ingestTokenSecret"
                bulkerTokenSecret: "$bulkerTokenSecret"
                syncctlTokenSecret: "$syncctlTokenSecret"

                ingestAuthToken: "$ingestAuthToken"
                bulkerAuthToken: "$bulkerAuthToken"
                syncctlAuthToken: "$syncctlAuthToken"
                consoleAuthToken: "service-admin-account:$consoleAuthToken"

                ingestAuthTokens: "$ingestAuthTokens"
                bulkerAuthTokens: "$bulkerAuthTokens"
                syncctlAuthTokens: "$syncctlAuthTokens"
                consoleAuthTokens: "$consoleAuthTokens"
              EOF
{{- end }}
