{{- if .Values.tokenGenerator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jitsu.fullname" . }}-token-generator-{{ sha1sum (toJson .Values) | substr 0 8 }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
  {{- with .Values.tokenGenerator.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
      {{- with (merge (deepCopy .Values.tokenGenerator.podAnnotations) .Values.global.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "jitsu.tokenGenerator.serviceAccountName" . }}
      {{- with (.Values.tokenGenerator.podSecurityContext | default .Values.global.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: token-generator
          {{- with (.Values.tokenGenerator.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.tokenGenerator.image.tag }}
          image: "{{ .Values.tokenGenerator.image.repository }}:{{ .Values.tokenGenerator.image.tag }}"
          {{- else }}
          {{- $v := semver .Capabilities.KubeVersion.Version }}
          image: "{{ .Values.tokenGenerator.image.repository }}:{{ printf "%d.%d.%d" $v.Major $v.Minor $v.Patch }}"
          {{- end }}
          env:
            - name: FULLNAME
              value: {{ include "jitsu.fullname" . }}
            - name: LABELS
              value: {{ include "jitsu.labels" . | fromYaml | toJson | quote }}
            - name: SECRET_LENGTH
              value: {{ .Values.tokenGenerator.secretLength | default "32" | quote }}
            - name: TOKEN_LENGTH
              value: {{ .Values.tokenGenerator.tokenLength | default "32" | quote }}
            - name: SALT_LENGTH
              value: {{ .Values.tokenGenerator.saltLength | default "32" | quote }}
          {{- with (.Values.tokenGenerator.resources | default .Values.global.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["python3", "-c"]
          args:
            - {{ .Files.Get "scripts/token-generator.py" | quote }}
      {{- with (.Values.tokenGenerator.nodeSelector | default .Values.global.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.tokenGenerator.affinity | default .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.tokenGenerator.tolerations | default .Values.global.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
