{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jitsu.fullname" . }}-migration-{{ include "jitsu.hash" . }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
  {{- with .Values.migration.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
      {{- with (merge (deepCopy .Values.migration.podAnnotations) .Values.global.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: "Never"
      serviceAccountName: {{ include "jitsu.serviceAccountName" . }}
      {{- with (.Values.migration.podSecurityContext | default .Values.global.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.tokenGenerator.enabled }}
        - name: wait-for-tokens
          {{- with (.Values.migration.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["job-wr", "{{ include "jitsu.fullname" . }}-token-generator-{{ include "jitsu.hash" . }}"]
          {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-postgresql
          {{- with (.Values.migration.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["service", "{{ .Release.Name }}-postgresql"]
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with (.Values.migration.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          command: {{ .Values.migration.command | toYaml | nindent 12 }}
          {{- if .Values.migration.envFrom }}
          envFrom:
            {{- toYaml .Values.migration.envFrom | nindent 12 }}
          {{- end }}
          env:
            {{- if and .Values.config.enabled .Values.migration.config.enabled }}
            {{- if or .databaseUrlFrom $.Values.config.databaseUrlFrom }}
            - name: DATABASE_URL
              valueFrom:
                {{- toYaml (.databaseUrlFrom | default $.Values.config.databaseUrlFrom) | nindent 4 }}
            {{- else }}
            - name: DATABASE_URL
              value: {{ .Values.migration.config.databaseUrl | default (include "jitsu.databaseUrl" .) | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.migration.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with (.Values.migration.nodeSelector | default .Values.global.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.migration.affinity | default .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.migration.tolerations | default .Values.global.affinity) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
