{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jitsu.fullname" . }}-migration-{{ include "jitsu.hash" . }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
  {{- with .Values.migration.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
      {{- with (merge (deepCopy .Values.migration.podAnnotations) .Values.global.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: "Never"
      serviceAccountName: {{ include "jitsu.serviceAccountName" . }}
      {{- with (.Values.migration.podSecurityContext | default .Values.global.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.tokenGenerator.enabled }}
        - name: wait-for-tokens
          {{- with (.Values.migration.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.k8s-wait-for.image.repository }}:{{ .Values.k8s-wait-for.image.tag }}"
          args: ["job-wr", "{{ include "jitsu.fullname" . }}-token-generator-{{ include "jitsu.hash" . }}"]
          {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-postgresql
          {{- with (.Values.migration.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.k8s-wait-for.image.repository }}:{{ .Values.k8s-wait-for.image.tag }}"
          args: ["service", "{{ .Release.Name }}-postgresql"]
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with (.Values.migration.securityContext | default .Values.global.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          command: {{ .Values.migration.command | toYaml | nindent 12 }}
          {{- if .Values.migration.envFrom }}
          envFrom:
            {{- toYaml .Values.migration.envFrom | nindent 12 }}
          {{- end }}
          env:
            {{- if and .Values.config.enabled .Values.migration.config.enabled }}
            {{- with .Values.migration.config }}
            {{- if or .databaseUrlFrom $.Values.config.databaseUrlFrom }}
            - name: DATABASE_URL
              valueFrom:
                {{- toYaml (.databaseUrlFrom | default $.Values.config.databaseUrlFrom) | nindent 16 }}
            {{- else }}
            - name: DATABASE_URL
              value: {{ .databaseUrl | default (include "jitsu.databaseUrl" $) | quote }}
            {{- end }}
            {{- if or .clickhouseHostFrom $.Values.config.clickhouseHttpHostFrom }}
            - name: CLICKHOUSE_HOST
              valueFrom:
                {{- toYaml (.clickhouseHostFrom | default $.Values.config.clickhouseHttpHostFrom) | nindent 4 }}
            {{- else }}
            - name: CLICKHOUSE_HOST
              value: {{ .clickhouseHost | default (include "jitsu.clickhouseHttpHost" $) | quote }}
            {{- end }}

            {{- if or .clickhouseDatabaseFrom $.Values.config.clickhouseDatabaseFrom }}
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                {{- toYaml (.clickhouseDatabaseFrom | default $.Values.config.clickhouseDatabaseFrom) | nindent 4 }}
            {{- else }}
            - name: CLICKHOUSE_DATABASE
              value: {{ .clickhouseDatabase | default (include "jitsu.clickhouseDatabase" $) | quote }}
            {{- end }}

            {{- if or .clickhouseUsernameFrom $.Values.config.clickhouseUsernameFrom }}
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                {{- toYaml (.clickhouseUsernameFrom | default $.Values.config.clickhouseUsernameFrom) | nindent 4 }}
            {{- else }}
            - name: CLICKHOUSE_USERNAME
              value: {{ .clickhouseUsername | default (include "jitsu.clickhouseUsername" $) | quote }}
            {{- end }}

            {{- if or .clickhousePasswordFrom $.Values.config.clickhousePasswordFrom }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                {{- toYaml (.clickhousePasswordFrom | default $.Values.config.clickhousePasswordFrom) | nindent 4 }}
            {{- else }}
            - name: CLICKHOUSE_PASSWORD
              value: {{ .clickhousePassword | default (include "jitsu.clickhousePassword" $) | quote }}
            {{- end }}

            {{- with (.clickhouseSsl | default $.Values.config.clickhouseSsl) }}
            - name: CLICKHOUSE_SSL
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with .Values.migration.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with (.Values.migration.nodeSelector | default .Values.global.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.migration.affinity | default .Values.global.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.migration.tolerations | default .Values.global.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
