{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jitsu.fullname" . }}-migration-{{ sha1sum (toJson .Values) | substr 0 8 }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
  {{- with .Values.migration.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: "Never"
      serviceAccountName: {{ include "jitsu.serviceAccountName" . }}
      initContainers:
        {{- if .Values.config.autoGenerateTokens }}
        - name: wait-for-tokens
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["job-wr", "{{ include "jitsu.fullname" . }}-auto-generate-tokens-{{ sha1sum (toJson .Values) | substr 0 8 }}"]
          {{- end }}
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-postgresql
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["service", "{{ .Release.Name }}-postgresql"]
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          command: [prisma]
          args: [db, push, --skip-generate, --schema, /app/schema.prisma]
          env:
            - name: DATABASE_URL
              value: {{ include "jitsu.databaseUrl" . | quote }}
            {{- with .Values.migration.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
{{- end }}
