{{- if and .Values.console.podDisruptionBudget.enabled .Values.console.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "jitsu.fullname" . }}-console
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
    {{- include "jitsu.console.selectorLabels" . | nindent 4 }}
spec:
  {{- with .Values.console.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.console.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jitsu.selectorLabels" . | nindent 6 }}
      {{- include "jitsu.console.selectorLabels" . | nindent 6 }}
{{- end }}
