{{- if and .Values.ingest.podDisruptionBudget.enabled .Values.ingest.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "jitsu.fullname" . }}-ingest
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
    {{- include "jitsu.ingest.selectorLabels" . | nindent 4 }}
spec:
  {{- with .Values.ingest.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.ingest.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jitsu.selectorLabels" . | nindent 6 }}
      {{- include "jitsu.ingest.selectorLabels" . | nindent 6 }}
{{- end }}
