{{- if .Values.config.syncctl.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jitsu.fullname" . }}-syncctl
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jitsu.fullname" . }}-syncctl
subjects:
  - kind: ServiceAccount
    name: {{ include "jitsu.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
